### ISSUE TITLE
It error when use other file without .py

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [twistedturtle/blender-scripting-toolbox#1]
This not a bug
But I think you need to add a blacklist to block other type files.

Because it will log error when you not edit the .py file. Bit annoying (although it didn't affect me much to edit the file)

For example：
```
Exception in helpers.h: unterminated string literal (detected at line 21) (<string>, line 21)

Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\blender-scripting-toolbox-main\strack.py", line 104, in _run_script
    at.as_module()
  File "G:\blender\36\3.6\scripts\modules\bpy_types.py", line 706, in as_module
    exec(self.as_string(), mod.__dict__)
  File "<string>", line 21
    // Converts an iterable container to a vector of int64's.
                                                          ^
SyntaxError: unterminated string literal (detected at line 21)

Still running

Exception in Hexagon.osl: invalid decimal literal (<string>, line 9)

Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\blender-scripting-toolbox-main\strack.py", line 104, in _run_script
    at.as_module()
  File "G:\blender\36\3.6\scripts\modules\bpy_types.py", line 706, in as_module
    exec(self.as_string(), mod.__dict__)
  File "<string>", line 9
    * Modified 1/4/2020 by Saul Espinosa for Redshift 3D
                                                      ^
SyntaxError: invalid decimal literal

Still running

Exception in ParallaxOcclusionMapping.osl: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<string>, line 2)

Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\blender-scripting-toolbox-main\strack.py", line 104, in _run_script
    at.as_module()
  File "G:\blender\36\3.6\scripts\modules\bpy_types.py", line 706, in as_module
    exec(self.as_string(), mod.__dict__)
  File "<string>", line 2
    Version: 001
             ^^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

Still running
```

**Comment by twistedturtle** [comment]
Thank you for your feedback. :smiley: 

I've made it so that other file types will still update if they change externally, but won't be run. 20ac632

The script/text will only be run if at least one of these criteria are met:

1. One of the first 30 lines starts with an import statement, eg `import math`, `from mathutils import Matrix`, etc
2. If external, the filename ends in `.py`.


Criterion 1 allows use of files without the `.py` extension, and ignores internal scripts/texts which shouldn't be run. Not sure how useful the latter is, as it only applies when the user runs it manually. 

There are several languages, that I know of, which could create a false positive, but I think they're unlikely to be found within Blender. If necessary, I can restrict it to imports of Blender modules which should prevent any false positives. It could also be extended to other terms such as `bl_info`.

The longest I've seen the python detection take is ~70us (limited testing), with the file stored on a hard drive and the import statement on line 30 (worst case). So it shouldn't be noticeable.

Please let me know what you think.

**Comment by BUGProtectionAssociation** [comment]
> Thank you for your feedback. 😃
> 
> I've made it so that other file types will still update if they change externally, but won't be run. [20ac632](https://github.com/twistedturtle/blender-scripting-toolbox/commit/20ac63245fe48c610d58461f1750c89befdd87f5)
> 
> The script/text will only be run if at least one of these criteria are met:
> 
> 1. One of the first 30 lines starts with an import statement, eg `import math`, `from mathutils import Matrix`, etc
> 2. If external, the filename ends in `.py`.
> 
> Criterion 1 allows use of files without the `.py` extension, and ignores internal scripts/texts which shouldn't be run. Not sure how useful the latter is, as it only applies when the user runs it manually.
> 
> There are several languages, that I know of, which could create a false positive, but I think they're unlikely to be found within Blender. If necessary, I can restrict it to imports of Blender modules which should prevent any false positives. It could also be extended to other terms such as `bl_info`.
> 
> The longest I've seen the python detection take is ~70us (limited testing), with the file stored on a hard drive and the import statement on line 30 (worst case). So it shouldn't be noticeable.
> 
> Please let me know what you think.

I just want to add a button to close the log if we not need it.

**Comment by twistedturtle** [comment]
The "log" consists of errors and output from the script, which is extremely useful if you're running a script. Anything other than python will cause an error and shouldn't be run as python (so this _was_ a bug, thank you for helping me fix it). The modifications should stop non-python files being run as scripts in the first place so there won't be an error to display. Whilst the method of python detection may change, this behaviour shouldn't.

Unless I'm missing something this should solve the issue, and is essentially what you originally suggested. Not a blocklist, but it achieves the same goal.

The only thing you might have to do is add an import statement to your python scripts, but you're likely to import at least one module anyway. If an external script is acceptable then use a .py extension (sounds like you already do) and you don't need an import statement.  I suppose I could check the name of internal texts for a .py extension, I may add that in.

If this isn't acceptable then please tell me what you'd prefer.
<hr></hr>

> I just want to add a button to close the log if we not need it.

There are already options to enable/disable output to the system console and the python console, but they're global, ie one option for all scripts. They apply to all errors and any other output from the script being run.

Do you want to disable the output per script/text?
Do you want some other behaviour?

**Comment by BUGProtectionAssociation** [comment]
> The "log" consists of errors and output from the script, which is extremely useful if you're running a script. Anything other than python will cause an error and shouldn't be run as python (so this _was_ a bug, thank you for helping me fix it). The modifications should stop non-python files being run as scripts in the first place so there won't be an error to display. Whilst the method of python detection may change, this behaviour shouldn't.
> 
> Unless I'm missing something this should solve the issue, and is essentially what you originally suggested. Not a blocklist, but it achieves the same goal.
> 
> The only thing you might have to do is add an import statement to your python scripts, but you're likely to import at least one module anyway. If an external script is acceptable then use a .py extension (sounds like you already do) and you don't need an import statement. I suppose I could check the name of internal texts for a .py extension, I may add that in.
> 
> If this isn't acceptable then please tell me what you'd prefer.
> 
> > I just want to add a button to close the log if we not need it.
> 
> There are already options to enable/disable output to the system console and the python console, but they're global, ie one option for all scripts. They apply to all errors and any other output from the script being run.
> 
> Do you want to disable the output per script/text? Do you want some other behaviour?

Maybe we can add support for OSL files. Because a lot of users will use them.
Instead of reporting an error because of a non-py file. Of course the other formats remain the same, recording errors to the log file (as it is now)

**Comment by twistedturtle** [comment]
>Maybe we can add support for OSL files. Because a lot of users will use them.

What support do you mean? At the moment they will be ignored (ie not run) and blender will deal with them how it deals with them. 

Any files that aren't python should not be run by the plugin and so will not cause an error.

There's already a new version, to get it, you need to re-install from a fresh download. You shouldn't get these errors with the new version, I don't. Please try it and see if it works for you.

>Of course the other formats remain the same, recording errors to the log file (as it is now)

Why would you want to run non-python as python?
